# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ KEK-10 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Configure NPM client
      working-directory: ./bank-client
      run: |
        echo "//npm.pkg.github.com/:_authToken=\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" >> .npmrc
        echo "always-auth: true" >> .npmrc
        
    - name: Npm client ci
      run: npm ci
      working-directory: ./bank-client

    - name: Npm client build
      run: npm run build --if-present
      working-directory: ./bank-client

    - name: Npm client test
      run: npm test
      working-directory: ./bank-client

    - name: Configure NPM server
      working-directory: ./bank-server
      run: |
        echo "//npm.pkg.github.com/:_authToken=\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" >> .npmrc
        echo "always-auth: true" >> .npmrc

    - name: Npm server ci
      run: npm ci
      working-directory: ./bank-server

    - name: Npm server build
      run: npm run build --if-present
      working-directory: ./bank-server

    - name: Npm server test
      run: npm test
      working-directory: ./bank-server
    
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: gamebank/releases
        registry: docker.io
        username: gamebank
        password: 2001vasia
